{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "Logistics Swagger",
        "description": "Cấu trúc sử dụng RESTful API",
        "license": {
            "name": "Made by Hoài Nhớ",
            "url": "logistics-dev.tk"
        }
    },
    "servers": [
        {
            "url": "http://localhost:3000/",
            "description": "Local host"
        },
        {
            "url": "/api/",
            "description": "Heroku"
        }
    ],
    "tags": [
        {
            "name": "http://localhost:3000",
            "description": "Các phương thức có thể sử dụng được :"
        }
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/orders?page={PAGE}&page_size={PAGE_SIZE}": {
            "get": {
                "tags": [
                    "Lấy danh sách Sale Order"
                ],
                "summary": "GET tất các các order",
                "parameters": [
                    {
                        "name": "PAGE",
                        "in": "path",
                        "required": true,
                        "description": "Số trang",
                        "type": "number"
                    },
                    {
                        "name": "PAGE_SIZE",
                        "in": "path",
                        "required": false,
                        "description": "Số phần tử cần lấy ( Default : 10 )",
                        "type": "number"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Orders"
                        }
                    }
                }
            }
        },
        "/order": {
            "post": {
                "tags": [
                    "Tạo Sale Order"
                ],
                "summary": "Tạo Sale Order mới",
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Order"
                            },
                            "example": {
                                "customerName": "Anh Tony",
                                "customerAddress": "TPHCM",
                                "customerPhone": "0123444444",
                                "receiverName": "Hoài Nhớ",
                                "receiverAddress": "Cà Mau",
                                "receiverPhone": "0113332222",
                                "isFreeShip": true,
                                "totalPrice": "99999",
                                "notes": "Hàng việt nam chất lượng cao",
                                "orderType": 1,
                                "quantity": "12",
                                "unit_id": 1,
                                "payment_id": 1,
                                "orderName": "Y Tế",
                                "products": [
                                    {
                                        "name": "Thuốc",
                                        "quantity": "1",
                                        "unit": 1
                                    },
                                    {
                                        "name": "Gạo",
                                        "quantity": "1",
                                        "unit": 1
                                    }
                                ],
                                "typeShip": "giao hàng nhanh"
                            }
                        }
                    }
                },
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    }
                }
            }
        },
        "/order/{id}": {
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "description": "ID là mã hóa đơn",
                    "type": "string"
                }
            ],
            "get": {
                "tags": [
                    "Tìm một Sale Order "
                ],
                "summary": "GET một order với ID ",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "Order có ID",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Order"
                        }
                    },
                    "404": {
                        "description": "Failed. Cat not found."
                    }
                }
            },
            "put": {
                "summary": "Cập nhật hóa đơn có ID",
                "tags": [
                    "Cập nhật một Sale Order"
                ],
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Order"
                            },
                            "example": {
                                "customerName": "Anh Tony",
                                "customerAddress": "TPHCM",
                                "customerPhone": "0123444444",
                                "receiverName": "Hoài Nhớ",
                                "receiverAddress": "Cà Mau",
                                "receiverPhone": "0113332222",
                                "isFreeShip": true,
                                "totalPrice": "99999",
                                "notes": "Hàng việt nam chất lượng cao nhất thế giới",
                                "quantity": "12",
                                "orderName": "Y Tế",
                                "unit_id": "3",
                                "orderType": "2",
                                "payment_id": "1",
                                "products": [
                                    {
                                        "id": 71,
                                        "name": "Thuốc chích",
                                        "quantity": 8,
                                        "unit_id": 1
                                    },
                                    {
                                        "name": "Thuốc Lắc cường độ mạnh",
                                        "quantity": 1,
                                        "unit_id": 2
                                    }
                                ]
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "ID Sale Order cần cập nhật",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Order"
                        }
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    },
                    "404": {
                        "description": "Failed. Cat not found."
                    }
                }
            },
            "delete": {
                "summary": "DELETE Hóa đơn với ID",
                "tags": [
                    "Xóa một Sale Order ( Xóa vĩnh viễn )"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "DELETE hóa đơn với ID",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    },
                    "404": {
                        "description": "Failed. Cat not found."
                    }
                }
            }
        },
        "/order/delete": {
            "delete": {
                "tags": [
                    "Xóa mềm một Sale Order ( Có thể Restore )"
                ],
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "type": "number"
                                }
                            },
                            "example": {
                                "idList": [
                                    5,
                                    7,
                                    8
                                ]
                            }
                        }
                    }
                },
                "summary": "Xóa Sale Order",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Order"
                        }
                    }
                }
            }
        },
        "/order/restore/{id}": {
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "description": "ID là mã hóa đơn",
                    "type": "string"
                }
            ],
            "patch": {
                "tags": [
                    "Khôi phục một Sale Order"
                ],
                "summary": "Khôi phục Sale Order",
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Order"
                        }
                    }
                }
            }
        },
        "/jobs?page={PAGE}&page_size={PAGE_SIZE}": {
            "get": {
                "tags": [
                    "Lấy danh sách công việc"
                ],
                "summary": "GET tất các các công việc",
                "parameters": [
                    {
                        "name": "PAGE",
                        "in": "path",
                        "required": true,
                        "description": "Số trang",
                        "type": "number"
                    },
                    {
                        "name": "PAGE_SIZE",
                        "in": "path",
                        "required": false,
                        "description": "Số phần tử cần lấy ( Default : 10 )",
                        "type": "number"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Jobs"
                        }
                    }
                }
            }
        },
        "/job": {
            "post": {
                "tags": [
                    "Tạo công việc"
                ],
                "summary": "Tạo công việc mới",
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Job"
                            },
                            "example": {
                                "nameJob": "Tiếp Viên Hàng Không",
                                "salaryBefore": 1000000,
                                "salaryAfter": 2000000,
                                "degree": "Đại Học",
                                "address": "TP HCM"
                            }
                        }
                    }
                },
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    }
                }
            }
        },
        "/jobs/{id}": {
            "parameters": [
                {
                    "name": "id",
                    "in": "path",
                    "required": true,
                    "description": "ID là mã hóa công việc",
                    "type": "string"
                }
            ],
            "get": {
                "tags": [
                    "Tìm một công việc "
                ],
                "summary": "GET một công việc với ID ",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "Công việc có ID",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Job"
                        }
                    },
                    "404": {
                        "description": "Failed. Cat not found."
                    }
                }
            },
            "put": {
                "summary": "Cập nhật công việc có ID",
                "tags": [
                    "Cập nhật một công việc"
                ],
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Job"
                            },
                            "example": {
                                "nameJob": "Designer",
                                "salaryBefore": 500000,
                                "salaryAfter": 800000,
                                "degree": "Cao Đẳng",
                                "address": "TP HCM"
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "ID công việc cần cập nhật",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Job"
                        }
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    },
                    "404": {
                        "description": "Failed. Cat not found."
                    }
                }
            },
            "delete": {
                "summary": "DELETE công việc với ID",
                "tags": [
                    "Xóa một công việc ( Xóa vĩnh viễn )"
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "description": "DELETE hóa đơn với ID",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/id"
                        }
                    },
                    "404": {
                        "description": "Failed. Cat not found."
                    }
                }
            }
        },
        "/requests?page={PAGE}&page_size={PAGE_SIZE}": {
            "get": {
                "tags": [
                    "Lấy danh sách yêu cầu đặt hàng"
                ],
                "summary": "GET tất các các yêu cầu đặt hàng",
                "parameters": [
                    {
                        "name": "PAGE",
                        "in": "path",
                        "required": true,
                        "description": "Số trang",
                        "type": "number"
                    },
                    {
                        "name": "PAGE_SIZE",
                        "in": "path",
                        "required": false,
                        "description": "Số phần tử cần lấy ( Default : 10 )",
                        "type": "number"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Request"
                        }
                    }
                }
            }
        },
        "/request": {
            "post": {
                "tags": [
                    "Tạo yêu cầu đặt hàng"
                ],
                "summary": "Tạo yêu cầu đặt hàng mới",
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Request"
                            },
                            "example": {
                                "fullname": "Long tóc xoăn",
                                "email": "long@gmail.com",
                                "phone": "0333333333",
                                "address": "TP HCM",
                                "typeProduct": "Thủy sản",
                                "weight": 10,
                                "fastShip": true,
                                "note": "Hàng đông lạnh"
                            }
                        }
                    }
                },
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    }
                }
            }
        },
        "/users?page={PAGE}&page_size={PAGE_SIZE}": {
            "get": {
                "tags": [
                    "Lấy danh sách tài khoản"
                ],
                "summary": "GET tất các các tài khoản",
                "parameters": [
                    {
                        "name": "PAGE",
                        "in": "path",
                        "required": true,
                        "description": "Số trang",
                        "type": "number"
                    },
                    {
                        "name": "PAGE_SIZE",
                        "in": "path",
                        "required": false,
                        "description": "Số phần tử cần lấy ( Default : 10 )",
                        "type": "number"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/Account"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "Đăng ký tài khoản"
                ],
                "summary": "Đăng ký tài khoản mới",
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Account"
                            },
                            "example": {
                                "email": "tester@gmail.com",
                                "password": "123123",
                                "fullname": "Tester",
                                "phone": "0909090127"
                            }
                        }
                    }
                },
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "Đăng nhập"
                ],
                "summary": "Đăng nhập",
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Login"
                            },
                            "example": {
                                "phone": "0909090127",
                                "password": "123123"
                            }
                        }
                    }
                },
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    }
                }
            }
        },
        "/admin/dashboard": {
            "post": {
                "tags": [
                    "Đăng nhập Dashboard"
                ],
                "summary": "Đăng nhập Dashboard",
                "requestBody": {
                    "description": "Các thuộc tính bắt buộc : ",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Login"
                            },
                            "example": {
                                "phone": "09090901215",
                                "password": "123123"
                            }
                        }
                    }
                },
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Failed. Bad post data."
                    }
                }
            }
        }
    },
    "definitions": {
        "id": {
            "properties": {
                "uuid": {
                    "type": "string"
                }
            }
        },
        "Order": {
            "type": "object",
            "properties": {
                "customerName": {
                    "type": "string"
                },
                "customerAddress": {
                    "type": "string"
                },
                "customerPhone": {
                    "type": "number"
                },
                "receiverName": {
                    "type": "string"
                },
                "receiverAddress": {
                    "type": "string"
                },
                "receiverPhone": {
                    "type": "number"
                },
                "isFreeShip": {
                    "type": "boolean"
                },
                "totalPrice": {
                    "type": "number"
                },
                "notes": {
                    "type": "string"
                },
                "orderType": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "unit_id": {
                    "type": "number"
                },
                "payment_id": {
                    "type": "number"
                },
                "products": {
                    "items": {
                        "$ref": "#/definitions/product"
                    }
                }
            }
        },
        "Orders": {
            "type": "array",
            "properties": {
                "orders": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/Order"
                    }
                }
            }
        },
        "product": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "unit": {
                    "type": "number"
                }
            }
        },
        "Job": {
            "type": "object",
            "properties": {
                "nameJob": {
                    "type": "string"
                },
                "salaryBefore": {
                    "type": "number"
                },
                "salaryAfter": {
                    "type": "number"
                },
                "degree": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                }
            }
        },
        "Jobs": {
            "type": "array",
            "properties": {
                "Jobs": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/Job"
                    }
                }
            }
        },
        "Request": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string"
                },
                "phone": {
                    "type": "number"
                },
                "email": {
                    "type": "string"
                },
                "address": {
                    "type": "string"
                },
                "typeProduct": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                },
                "fastShip": {
                    "type": "boolean"
                },
                "note": {
                    "type": "string"
                }
            }
        },
        "Requests": {
            "type": "array",
            "properties": {
                "Jobs": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/Request"
                    }
                }
            }
        },
        "Account": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string"
                },
                "phone": {
                    "type": "number"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "Accounts": {
            "type": "array",
            "properties": {
                "Jobs": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/Account"
                    }
                }
            }
        },
        "Login": {
            "type": "object",
            "properties": {
                "phone": {
                    "type": "number"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}